# Generated by Django 5.1.1 on 2024-09-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0002_fix_model_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmeticorder',
            name='category',
            field=models.CharField(default='', max_length=50, verbose_name='Категория косметики'),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='volume',
            field=models.IntegerField(verbose_name='Объем'),
        ),
    ]
