# Generated by Django 5.1.1 on 2024-10-05 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0003_add_field_to_cosmeticorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmeticorder',
            name='date_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cosmeticorder',
            name='date_formation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cosmeticorder',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_formulation', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='cosmeticorder',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория косметики'),
        ),
        migrations.AlterField(
            model_name='cosmeticorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_formulation', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
