# Generated by Django 5.1.1 on 2024-10-29 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0004_add_field_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmeticorder',
            name='category',
        ),
        migrations.AddField(
            model_name='cosmeticorder',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название косметики'),
        ),
        migrations.AlterField(
            model_name='chemicalelement',
            name='img_path',
            field=models.CharField(default='', max_length=255, verbose_name='Путь к изображению'),
        ),
        migrations.AlterField(
            model_name='cosmeticorder',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_formulation', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='cosmeticorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_formulation', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='ordercomponent',
            name='chemical_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cosmetics.chemicalelement', verbose_name='Химический элемент'),
        ),
        migrations.AlterField(
            model_name='ordercomponent',
            name='dosage',
            field=models.FloatField(default=0, verbose_name='Дозировка'),
        ),
        migrations.AlterField(
            model_name='ordercomponent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='cosmetics.cosmeticorder'),
        ),
    ]
