# Generated by Django 5.1.1 on 2024-10-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0005_make_dosage_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomponent',
            name='dosage',
            field=models.FloatField(default=0, verbose_name='Дозировка'),
        ),
    ]
