# Generated by Django 5.1.1 on 2024-11-19 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0007_remove_cascade_deletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmeticorder',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='cosmeticorder',
            name='user',
        ),
        migrations.AddField(
            model_name='cosmeticorder',
            name='adverse_effects_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество побочных эффектов'),
        ),
        migrations.AddField(
            model_name='cosmeticorder',
            name='formulation_chemist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_formulations', to=settings.AUTH_USER_MODEL, verbose_name='Химик-аналитик'),
        ),
        migrations.AddField(
            model_name='cosmeticorder',
            name='technologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_formulations', to=settings.AUTH_USER_MODEL, verbose_name='Технолог'),
        ),
    ]
