# Generated by Django 5.1.1 on 2024-12-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0008_rename_user_and_manager_add_adverse_effects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmeticorder',
            name='adverse_effects_count',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество побочных эффектов'),
        ),
    ]
